{
    "20190010_Sachinandan Tiwari": {
        "studentName": "20190010_Sachinandan Tiwari",
        "className": "Sri Vamana",
        "hostler": "N",
        "admissionYear": "2019",
        "grandTotal": "5640",
        "open": true,
        "items": [
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Cooking Experience",
                "item": "Weekly Cooking Class",
                "price": "500",
                "qty": "1",
                "total": "500",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 2
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Notebooks",
                "item": "Register",
                "price": "80",
                "qty": "4",
                "total": "320",
                "grandTotal": "5640",
                "min": "3",
                "max": "5",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 3
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Notebooks",
                "item": "Hindi Notebook",
                "price": "60",
                "qty": "3",
                "total": "180",
                "grandTotal": "5640",
                "min": "2",
                "max": "4",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 4
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Notebooks",
                "item": "English Notebook",
                "price": "60",
                "qty": "3",
                "total": "180",
                "grandTotal": "5640",
                "min": "2",
                "max": "4",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 5
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Others",
                "item": "Sweat Shirt",
                "price": "700",
                "qty": "1",
                "total": "700",
                "grandTotal": "5640",
                "min": "1",
                "max": "2",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 6
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Others",
                "item": "Student Card",
                "price": "100",
                "qty": "1",
                "total": "100",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 7
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Others",
                "item": "Parent Card",
                "price": "100",
                "qty": "1",
                "total": "100",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 8
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Others",
                "item": "March (Half) + April Fee ",
                "price": "3000",
                "qty": "1",
                "total": "3000",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 9
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Books",
                "item": "Hindi Book",
                "price": "120",
                "qty": "1",
                "total": "120",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 10
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Books",
                "item": "English Book",
                "price": "130",
                "qty": "1",
                "total": "130",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 11
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Books",
                "item": "Maths Book",
                "price": "150",
                "qty": "1",
                "total": "150",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 12
            },
            {
                "studentName": "20190010_Sachinandan Tiwari",
                "hostler": "N",
                "className": "Sri Vamana",
                "admissionYear": "2019",
                "category": "Books",
                "item": "Science Book",
                "price": "160",
                "qty": "1",
                "total": "160",
                "grandTotal": "5640",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "5640",
                "rowIndex": 13
            }
        ]
    },
    "20210013_Madhav Sain": {
        "studentName": "20210013_Madhav Sain",
        "className": "Sri Madhusudana",
        "hostler": "Y",
        "admissionYear": "2021",
        "grandTotal": "6600",
        "open": false,
        "items": [
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Necessary Items",
                "item": "Bedsheets",
                "price": "200",
                "qty": "2",
                "total": "400",
                "grandTotal": "6600",
                "min": "2",
                "max": "4",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 14
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Necessary Items",
                "item": "Gurukul T-Shirts",
                "price": "380",
                "qty": "2",
                "total": "760",
                "grandTotal": "6600",
                "min": "2",
                "max": "2",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 15
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Cooking Experience",
                "item": "Weekly Cooking Class",
                "price": "500",
                "qty": "1",
                "total": "500",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 16
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Notebooks",
                "item": "Register",
                "price": "80",
                "qty": "3",
                "total": "240",
                "grandTotal": "6600",
                "min": "3",
                "max": "5",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 17
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Notebooks",
                "item": "Hindi Notebook",
                "price": "60",
                "qty": "2",
                "total": "120",
                "grandTotal": "6600",
                "min": "2",
                "max": "4",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 18
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Notebooks",
                "item": "English Notebook",
                "price": "60",
                "qty": "2",
                "total": "120",
                "grandTotal": "6600",
                "min": "2",
                "max": "4",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 19
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Others",
                "item": "Sweat Shirt",
                "price": "700",
                "qty": "1",
                "total": "700",
                "grandTotal": "6600",
                "min": "1",
                "max": "2",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 20
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Others",
                "item": "Student Card",
                "price": "100",
                "qty": "1",
                "total": "100",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 21
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Others",
                "item": "Parent Card",
                "price": "100",
                "qty": "1",
                "total": "100",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 22
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Others",
                "item": "March (Half) + April Fee ",
                "price": "3000",
                "qty": "1",
                "total": "3000",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 23
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Books",
                "item": "Hindi Book",
                "price": "120",
                "qty": "1",
                "total": "120",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 24
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Books",
                "item": "English Book",
                "price": "130",
                "qty": "1",
                "total": "130",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 25
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Books",
                "item": "Maths Book",
                "price": "150",
                "qty": "1",
                "total": "150",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 26
            },
            {
                "studentName": "20210013_Madhav Sain",
                "hostler": "Y",
                "className": "Sri Madhusudana",
                "admissionYear": "2021",
                "category": "Books",
                "item": "Science Book",
                "price": "160",
                "qty": "1",
                "total": "160",
                "grandTotal": "6600",
                "min": "1",
                "max": "1",
                "comments": "",
                "deliveryStatus": "pending",
                "deliveredQty": "",
                "formStatus": "paymentRecd",
                "adminCardType": "Blue",
                "amountRecd": "4500",
                "rowIndex": 27
            }
        ]
    }
}