
//response with request
{
    "status": true,
    "response": [
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Necessary Items",
            "item": "Tooth Brush",
            "price": "40",
            "qty": "2",
            "total": "80",
            "grandTotal": "3150",
            "min": "1",
            "max": "2",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 2
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Necessary Items",
            "item": "Tooth Paste",
            "price": "90",
            "qty": "2",
            "total": "180",
            "grandTotal": "3150",
            "min": "1",
            "max": "2",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 3
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Necessary Items",
            "item": "Kurta",
            "price": "450",
            "qty": "3",
            "total": "1350",
            "grandTotal": "3150",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 4
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Cooking Experience",
            "item": "Weekly Cooking Class",
            "price": "500",
            "qty": "1",
            "total": "500",
            "grandTotal": "3150",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 5
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Notebooks",
            "item": "Register",
            "price": "80",
            "qty": "3",
            "total": "240",
            "grandTotal": "3150",
            "min": "3",
            "max": "5",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 6
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Notebooks",
            "item": "Hindi Notebook",
            "price": "60",
            "qty": "2",
            "total": "120",
            "grandTotal": "3150",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 7
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Notebooks",
            "item": "English Notebook",
            "price": "60",
            "qty": "2",
            "total": "120",
            "grandTotal": "3150",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 8
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Books",
            "item": "Hindi Book",
            "price": "120",
            "qty": "1",
            "total": "120",
            "grandTotal": "3150",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 9
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Books",
            "item": "English Book",
            "price": "130",
            "qty": "1",
            "total": "130",
            "grandTotal": "3150",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 10
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Books",
            "item": "Maths Book",
            "price": "150",
            "qty": "1",
            "total": "150",
            "grandTotal": "3150",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 11
        },
        {
            "studentName": "20190006_Kavya Varshney",
            "studentNameDisplay": "Kavya Varshney",
            "className": "Sri Hrishikesha",
            "classNameDisplay": "IX",
            "category": "Books",
            "item": "Science Book",
            "price": "160",
            "qty": "1",
            "total": "160",
            "grandTotal": "3150",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 12
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Necessary Items",
            "item": "Tooth Brush",
            "price": "40",
            "qty": "2",
            "total": "80",
            "grandTotal": "3660",
            "min": "1",
            "max": "2",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 13
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Necessary Items",
            "item": "Tooth Paste",
            "price": "90",
            "qty": "1",
            "total": "90",
            "grandTotal": "3660",
            "min": "1",
            "max": "2",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 14
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Necessary Items",
            "item": "Dhoti",
            "price": "350",
            "qty": "3",
            "total": "1050",
            "grandTotal": "3660",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 15
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Necessary Items",
            "item": "Kurta",
            "price": "450",
            "qty": "2",
            "total": "900",
            "grandTotal": "3660",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 16
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Cooking Experience",
            "item": "Weekly Cooking Class",
            "price": "500",
            "qty": "1",
            "total": "500",
            "grandTotal": "3660",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 17
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Notebooks",
            "item": "Register",
            "price": "80",
            "qty": "3",
            "total": "240",
            "grandTotal": "3660",
            "min": "3",
            "max": "5",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 18
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Notebooks",
            "item": "Hindi Notebook",
            "price": "60",
            "qty": "2",
            "total": "120",
            "grandTotal": "3660",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 19
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Notebooks",
            "item": "English Notebook",
            "price": "60",
            "qty": "2",
            "total": "120",
            "grandTotal": "3660",
            "min": "2",
            "max": "4",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 20
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Books",
            "item": "Hindi Book",
            "price": "120",
            "qty": "1",
            "total": "120",
            "grandTotal": "3660",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 21
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Books",
            "item": "English Book",
            "price": "130",
            "qty": "1",
            "total": "130",
            "grandTotal": "3660",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 22
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Books",
            "item": "Maths Book",
            "price": "150",
            "qty": "1",
            "total": "150",
            "grandTotal": "3660",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 23
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "Books",
            "item": "Science Book",
            "price": "160",
            "qty": "1",
            "total": "160",
            "grandTotal": "3660",
            "min": "1",
            "max": "1",
            "comments": "",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "submitted",
            "rowIndex": 24
        },
        {
            "studentName": "20190008_Krishna Yadav",
            "studentNameDisplay": "Krishna Yadav",
            "className": "Sri Trivikrama",
            "classNameDisplay": "VI",
            "category": "",
            "item": "",
            "price": "",
            "qty": "",
            "total": "",
            "grandTotal": "",
            "min": "",
            "max": "",
            "comments": "test",
            "deliveryStatus": "pending",
            "deliveredQty": "",
            "formStatus": "resubmitted",
            "rowIndex": 25
        }
    ],
    "request": {
        "apiType": "RETRIEVE_STUDENT_SUBMISSIONS",
        "inputData": {}
    }
}